global using AudiophileEcommerceWebsite.ViewModels;
global using AudiophileEcommerceWebsite.Models;
global using AudiophileEcommerceWebsite.Entities;
global using AutoMapper;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using FluentValidation.AspNetCore;
global using AudiophileEcommerceWebsite.Validators;
global using Microsoft.AspNetCore.Authorization;